config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout' => 'sessions#destroy'

  resources :events, only: [:show] do
    get 'votes/categories', to: 'votes#categories'
    get 'votes/completions', to: 'votes#completions'
    get 'entries/categories', to: 'entries#categories'
    get 'entries/completions', to: 'entries#completions'

    resources :entries, only: [:new, :create, :index, :show]
    resources :votes, only: [:create]
    resources :rankings, only: [:index]
    resources :comments, only: [:index, :show]
  end

  namespace :admin do
    resources :events, only: [:index, :new, :create, :show, :update]
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_event
  skip_before_action :logged_in_user, only: %i[index show]
  before_action :check_closed_event

  def index
    votes = Vote.for_event(@event.id)
    @food_grouped_comments  = votes.for_category('food').fetch_group_comment
    @drink_grouped_comments = votes.for_category('drink').fetch_group_comment
    @lt_grouped_comments    = votes.for_category('lt').fetch_group_comment
  end

  def show
    @entry = Entry.find(params[:id])
    @entry_comments = Vote.for_event(@event.id).where(entry_id: @entry.id).where.not(comment: [nil, ''])
  end

  private

  def check_closed_event
    return if @event.closed?

    redirect_to event_path(@event), alert: 'このページは現在公開されていません。'
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/views/comments/index.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded-md shadow-md">
  <div class="mb-12">
    <h2 class="text-2xl font-bold mb-6 border-b pb-2 text-center lg:text-left">飯王に関するコメント</h2>
    <ul class="space-y-4">
      <% @food_grouped_comments.each do |group| %>
        <li class="bg-white border border-gray-300 p-4 rounded-lg transition duration-200 ease-in-out shadow-sm flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div class="w-full">
            <p class="text-lg font-semibold"><%= "#{group.name}さん" %></p>
            <p class="break-words whitespace-normal"><%= "#{group.title}" %></p>
          </div>
          <%= link_to "コメントを表示", event_comment_path(@event, group.entry_id), class: "bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 transition duration-200 ease-in-out mt-2 w-full text-center sm:mt-0 sm:w-auto sm:ml-4" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="mb-12">
    <h2 class="text-2xl font-bold mb-6 border-b pb-2 text-center lg:text-left">酒王に関するコメント</h2>
    <ul class="space-y-4">
      <% @drink_grouped_comments.each do |group| %>
        <li class="bg-white border border-gray-300 p-4 rounded-lg transition duration-200 ease-in-out shadow-sm flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div class="w-full">
            <p class="text-lg font-semibold"><%= "#{group.name}さん" %></p>
            <p class="break-words whitespace-normal"><%= "#{group.title}" %></p>
          </div>
          <%= link_to "コメントを表示", event_comment_path(@event, group.entry_id), class: "bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 transition duration-200 ease-in-out mt-2 w-full text-center sm:mt-0 sm:w-auto sm:ml-4" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="mb-12">
    <h2 class="text-2xl font-bold mb-6 border-b pb-2 text-center lg:text-left">LT王に関するコメント</h2>
    <ul class="space-y-4">
      <% @lt_grouped_comments.each do |group| %>
        <li class="bg-white border border-gray-300 p-4 rounded-lg transition duration-200 ease-in-out shadow-sm flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div class="w-full">
            <p class="text-lg font-semibold"><%= "#{group.name}さん" %></p>
            <p class="break-words whitespace-normal"><%= "#{group.title}" %></p>
          </div>
          <%= link_to "コメントを表示", event_comment_path(@event, group.entry_id), class: "bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 transition duration-200 ease-in-out mt-2 w-full text-center sm:mt-0 sm:w-auto sm:ml-4" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="text-center mt-8">
    <%= link_to "戻る", login_path %>
  </div>
  <br>
  <br>
</div>

app/views/comments/show.html.erb
<% set_meta_tags(
  og: {
    title: "【#{@entry.title}】への感想です",
    description: "頂いたすべてのコメントを掲載しています",
    image: image_url("tokyu.png"),
    url: request.original_url,
    type: 'website'
  },
  twitter: {
    card: "summary"
  }
) %>

<div class="container mx-auto px-4 py-8 lg:px-8 lg:w-3/4">
  <h1 class="text-2xl font-bold mb-6 text-center">コメント一覧</h1>
  <div class="font-semibold ml-3">
    <p><i class="fa-solid fa-user"></i> <%= @entry.user.name %> さん</p>
    <p class="whitespace-normal"><i class="fa-solid fa-star"></i> <%= @entry.title %></p>
  </div>
  <br>
  <ul class="space-y-4">
    <% @entry_comments.each do |comment| %>
      <li class="bg-gray-100 p-4 rounded-lg shadow-smt">
        <p class="text-lg"><%= comment.comment %></p>
      </li>
    <% end %>
  </ul>
  <br>
  <div class="text-center">
    <p class="text-xs">結果をシェアする</p>
    <%= link_to "https://twitter.com/intent/tweet?text=【#{ @entry.title }は感想をもらったよ！】&hashtags=tqrk15&url=#{ event_comment_url(@event, @entry) }", target: "_blank" do %>
      <i class="fa-brands fa-square-x-twitter"></i>
    <% end %>
  </div>
  <div class="text-center mt-8">
    <%= link_to "戻る", event_comments_path(@event) %>
  </div>
</div>
<br>
<br>