config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout' => 'sessions#destroy'

  resources :events, only: [:show] do
    get 'votes/categories', to: 'votes#categories'
    get 'votes/completions', to: 'votes#completions'
    get 'entries/categories', to: 'entries#categories'
    get 'entries/completions', to: 'entries#completions'

    resources :entries, only: [:new, :create, :index, :show]
    resources :votes, only: [:create]
    resources :rankings, only: [:index]
    resources :comments, only: [:index, :show]
  end

  namespace :admin do
    resources :events, only: [:index, :new, :create, :show, :update]
  end
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  has_many :votes, dependent: :destroy
  has_one_attached :image

  belongs_to :user
  belongs_to :category
  belongs_to :event
  validates :title, presence: true
  validates :description, length: { maximum: 300 }
  validate :image_type

  private

  def image_type
    allowed_types = ['image/jpeg', 'image/png', 'image/gif']
    errors.add(:image, 'はjpeg,pngまたはgif形式でアップロードしてください') if image.attached? && !image.blob.content_type.in?(allowed_types)
  end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

class EntriesController < ApplicationController
  include AdminHelper
  before_action :set_event
  before_action :require_admin, only: [:new], if: proc { params[:category] == 'lt' }
  before_action :check_entry_period, only: %i[new create]
  before_action :check_event_status

  def categories; end

  def new
    category = params[:category]
    @category = Category.find_by(category_name: category)
    @entry = Entry.new(event: @event)
    render_template(category, 'new')
  end

  def create
    @entry = current_user.entries.new(entry_params.merge(event: @event))
    category = params[:category]
    if @entry.save
      redirect_to event_entries_completions_path(@event, category:)
    else
      redirect_to new_event_entry_path(@event, category:), flash: { error: @entry.errors.full_messages.to_sentence }
    end
  end

  def completions
    @category = params[:category]
  end

  def index
    category = params[:category]
    category_id = Category.find_by(category_name: category).id
    @entries = @event.entries.with_attached_image.includes(:user).where(category_id:)
    render_template(category, 'index')
  end

  def show
    @entry = @event.entries.find(params[:id])
    @name = @entry.user.name
    @vote = Vote.new
    @category = params[:category]
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :category_id, :image)
  end

  def render_template(category, action_name)
    case category
    when 'food'
      render "#{action_name}_food"
    when 'drink'
      render "#{action_name}_drink"
    when 'lt'
      render "#{action_name}_lt"
    end
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def check_entry_period
    return if params[:category] == 'lt'

    redirect_to event_path(@event), alert: '現在、エントリーは受付けていません。' if !@event.open?
  end
end

app/helpers/entries_helper.rb
# frozen_string_literal: true

module EntriesHelper
  def user_entries_by_category(event, category_name)
    current_user.entries
                .joins(:category)
                .where(event_id: event.id)
                .where(categories: { category_name: })
  end
end

app/views/entries/categories.html.erb
<div class="text-center">
  <h1 class="text-3xl font-bold text-gray-800">エントリーする</h1>
  <h2 class="mt-8 text-2xl pb-5">飯王に登録する</h2>
  <%= link_to new_event_entry_path(@event, category: 'food'), class: 'inline-flex items-center justify-center w-12 h-12 bg-blue-500 text-white rounded-full hover:bg-blue-700' do %>
    <i class="fa-solid fa-utensils"></i>
  <% end %>
  <h2 class="mt-8 text-2xl pb-5">酒王に登録する</h2>
  <%= link_to new_event_entry_path(@event, category: 'drink'), class: 'inline-flex items-center justify-center w-12 h-12 bg-blue-500 text-white rounded-full hover:bg-blue-700' do %>
    <i class="fa-solid fa-wine-glass"></i>
  <% end %>
  <div class="mt-14">
    <%= link_to root_path, class: 'btn btn-primary' do %>
      <i class="fa-solid fa-rotate-left"></i> 戻る
    <% end %>
  </div>
</div>

app/views/entries/completions.html.erb
<div class="max-w-lg mx-auto p-6 bg-white rounded-md sm:shadow-md text-center space-y-4">
  <i class="fa-regular fa-circle-check text-green-500 text-5xl mb-4"></i>
  <h1 class="text-3xl font-bold mb-2">登録が完了しました</h1>
  <h2 class="text-xl text-gray-700">ご参加ありがとうございます！</h2>
  <div>
    <%= link_to "続けてエントリーする", new_event_entry_path(@event, category: @category), class: "bg-blue-500 text-white px-6 py-3 rounded-full hover:bg-blue-600 inline-block mt-6 transition duration-300 ease-in-out" %>
  </div>
  <div>
    <%= link_to "TOPへ戻る", root_path, class: "bg-blue-500 text-white px-6 py-3 rounded-full hover:bg-blue-600 inline-block mt-6 transition duration-300 ease-in-out" %>
  </div>
</div>

app/views/entries/entries_drink.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded-md shadow-md">
  <h1 class="text-3xl font-bold mb-6 text-center">投票先を選ぶ</h1>
  <div class="max-w-2xl mx-auto p-2 bg-white rounded-lg shadow-md mb-8">
    <p class="text-center text-gray-700 mb-4">
      投票できる数: <span class="font-semibold text-blue-500"><%= remind_vote_count('drink') %></span>票
    </p>
    <% if voted_entries('drink').present? %>
      <p class="text-base mb-4 text-gray-600 text-left md:text-center">あなたが投票したのは以下のエントリーです</p>
      <ul class=" text-gray-700">
        <% voted_entries('drink').each do |entry| %>
          <li class="py-1">
            <span><%= entry[:user_name] %></span>さんの「<%= entry[:title] %>」
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if @entries.present? %>
    <ul class="space-y-4">
      <% @entries.each do |entry| %>
        <li class="p-4 border border-gray-300 rounded-md flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div class="flex items-center flex-1 mb-2 sm:mb-0 sm:pr-4 border-b sm:border-none pb-2 sm:pb-0 w-full">
            <% if entry.image.attached? %>
              <%= image_tag entry.image.variant(resize: "300x300"), class: "w-24 h-24 object-cover mr-4 flex-shrink-0" %>
            <% end %>
            <div>
              <p class="text-lg font-semibold"><%= entry.user.name %></p>
              <p class="text-gray-700"><%= entry.title %></p>
              <p class="text-gray-700 text-xs mt-2"><%= entry.description %></p>
            </div>
          </div>
          <div class="mt-4 sm:mt-0 sm:ml-5 w-full sm:w-auto text-center">
            <%= link_to '選択する', entry_path(entry, category: 'drink'), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 inline-block min-w-[120px] text-center ml-5" %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center text-gray-500">エントリーされていません</p>
  <% end %>
</div>
</div>
<div class="mt-8 text-center">
  <%= link_to votes_categories_path, class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>
<br>
<br>

app/views/entries/entries_food.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded-md shadow-md">
  <h1 class="text-3xl font-bold mb-6 text-center">投票先を選ぶ</h1>
  <div class="max-w-2xl mx-auto p-2 bg-white rounded-lg shadow-md mb-8">
    <p class="text-center text-gray-700 mb-4">
      投票できる数: <span class="font-semibold text-blue-500"><%= remind_vote_count('food') %></span>票
    </p>
    <% if voted_entries('food').present? %>
      <p class="text-base mb-4 text-gray-600 text-left md:text-center">あなたが投票したのは以下のエントリーです</p>
      <ul class="text-gray-700">
        <% voted_entries('food').each do |entry| %>
          <li class="py-1">
            <span><%= entry[:user_name] %></span>さんの「<%= entry[:title] %>」
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <% if @entries.present? %>
    <ul class="space-y-4">
      <% @entries.each do |entry| %>
        <li class="p-4 border border-gray-300 rounded-md flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div class="flex items-center flex-1 mb-2 sm:mb-0 sm:pr-4 border-b sm:border-none pb-2 sm:pb-0 w-full">
            <% if entry.image.attached? %>
              <%= image_tag entry.image.variant(resize: "300x300"), class: "w-24 h-24 object-cover mr-4 flex-shrink-0" %>
            <% end %>
            <div>
              <p class="text-lg font-semibold"><%= entry.user.name %></p>
              <p class="text-gray-700"><%= entry.title %></p>
              <p class="text-gray-700 text-xs mt-2"><%= entry.description %></p>
            </div>
          </div>
          <div class="mt-4 sm:mt-0 sm:ml-5 w-full sm:w-auto text-center">
            <%= link_to '選択する', entry_path(entry, category: 'food'), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 inline-block min-w-[120px] text-center ml-5" %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center text-gray-500">エントリーされていません</p>
  <% end %>
</div>

<div class="mt-8 text-center">
  <%= link_to votes_categories_path, class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>
<br>
<br>

app/views/entries/entries_lt.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded-md shadow-md">
  <h1 class="text-3xl font-bold mb-6 text-center">投票先を選ぶ</h1>
  <div class="max-w-2xl mx-auto p-2 bg-white rounded-lg shadow-md mb-8">
    <p class="text-center text-gray-700 mb-4">
      投票できる数: <span class="font-semibold text-blue-500"><%= remind_vote_count('lt') %></span>票
    </p>
    <% if voted_entries('lt').present? %>
      <p class="text-base mb-4 text-gray-600 text-left md:text-center">あなたが投票したのは以下のエントリーです</p>
      <ul class=" text-gray-700">
        <% voted_entries('lt').each do |entry| %>
          <li class="py-1">
            <span><%= entry[:user_name] %></span>さんの「<%= entry[:title] %>」
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if @entries.present? %>
    <ul class="space-y-4">
      <% @entries.each do |entry| %>
        <li class="p-4 border border-gray-300 rounded-md flex justify-between items-center">
          <div>
            <p class="text-lg font-semibold"><%= entry.user.name %></p>
            <p class="text-gray-700"><%= entry.title %></p>
          </div>
          <%= link_to '選択する', entry_path(entry, category: 'lt'), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 inline-block min-w-[120px] text-center ml-5" %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center text-gray-500">エントリーされていません</p>
  <% end %>
</div>
<div class="mt-8 text-center">
  <%= link_to votes_categories_path, class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>
<br>
<br>

app/views/entries/index_drink.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded-md shadow-md">
  <h1 class="text-3xl font-bold mb-6 text-center">投票先を選ぶ</h1>
  <div class="max-w-2xl mx-auto p-2 bg-white rounded-lg shadow-md mb-8">
    <p class="text-center text-gray-700 mb-4">
      投票できる数: <span class="font-semibold text-blue-500"><%= remind_vote_count(@event, 'drink') %></span>票
    </p>
    <% if voted_entries(@event, 'drink').present? %>
      <p class="text-base mb-4 text-gray-600 text-left md:text-center">あなたが投票したのは以下のエントリーです</p>
      <ul class=" text-gray-700">
        <% voted_entries(@event, 'drink').each do |entry| %>
          <li class="py-1">
            <span><%= entry[:user_name] %></span>さんの「<%= entry[:title] %>」
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if @entries.present? %>
    <ul class="space-y-4">
      <% @entries.each do |entry| %>
        <li class="p-4 border border-gray-300 rounded-md flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div class="flex items-center flex-1 mb-2 sm:mb-0 sm:pr-4 border-b sm:border-none pb-2 sm:pb-0 w-full">
            <% if entry.image.attached? %>
              <%= image_tag entry.image.variant(resize: "300x300"), class: "w-24 h-24 object-cover mr-4 flex-shrink-0" %>
            <% end %>
            <div>
              <p class="text-lg font-semibold"><%= entry.user.name %></p>
              <p class="text-gray-700"><%= entry.title %></p>
              <p class="text-gray-700 text-xs mt-2"><%= entry.description %></p>
            </div>
          </div>
          <div class="mt-4 sm:mt-0 sm:ml-5 w-full sm:w-auto text-center">
            <%= link_to '選択する', event_entry_path(@event, entry, category: 'drink'), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 inline-block min-w-[120px] text-center ml-5" %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center text-gray-500">エントリーされていません</p>
  <% end %>
</div>
</div>
<div class="mt-8 text-center">
  <%= link_to event_votes_categories_path(@event), class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>
<br>
<br>

app/views/entries/index_food.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded-md shadow-md">
  <h1 class="text-3xl font-bold mb-6 text-center">投票先を選ぶ</h1>
  <div class="max-w-2xl mx-auto p-2 bg-white rounded-lg shadow-md mb-8">
    <p class="text-center text-gray-700 mb-4">
      投票できる数: <span class="font-semibold text-blue-500"><%= remind_vote_count(@event, 'food') %></span>票
    </p>
    <% if voted_entries(@event, 'food').present? %>
      <p class="text-base mb-4 text-gray-600 text-left md:text-center">あなたが投票したのは以下のエントリーです</p>
      <ul class="text-gray-700">
        <% voted_entries(@event, 'food').each do |entry| %>
          <li class="py-1">
            <span><%= entry[:user_name] %></span>さんの「<%= entry[:title] %>」
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <% if @entries.present? %>
    <ul class="space-y-4">
      <% @entries.each do |entry| %>
        <li class="p-4 border border-gray-300 rounded-md flex flex-col sm:flex-row justify-between items-start sm:items-center">
          <div class="flex items-center flex-1 mb-2 sm:mb-0 sm:pr-4 border-b sm:border-none pb-2 sm:pb-0 w-full">
            <% if entry.image.attached? %>
              <%= image_tag entry.image.variant(resize: "300x300"), class: "w-24 h-24 object-cover mr-4 flex-shrink-0" %>
            <% end %>
            <div>
              <p class="text-lg font-semibold"><%= entry.user.name %></p>
              <p class="text-gray-700"><%= entry.title %></p>
              <p class="text-gray-700 text-xs mt-2"><%= entry.description %></p>
            </div>
          </div>
          <div class="mt-4 sm:mt-0 sm:ml-5 w-full sm:w-auto text-center">
            <%= link_to '選択する', event_entry_path(@event, entry, category: 'food'), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 inline-block min-w-[120px] text-center ml-5" %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center text-gray-500">エントリーされていません</p>
  <% end %>
</div>

<div class="mt-8 text-center">
  <%= link_to event_votes_categories_path(@event), class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>
<br>
<br>

app/views/entries/index_lt.html.erb
<div class="max-w-4xl mx-auto p-6 bg-white rounded-md shadow-md">
  <h1 class="text-3xl font-bold mb-6 text-center">投票先を選ぶ</h1>
  <div class="max-w-2xl mx-auto p-2 bg-white rounded-lg shadow-md mb-8">
    <p class="text-center text-gray-700 mb-4">
      投票できる数: <span class="font-semibold text-blue-500"><%= remind_vote_count(@event, 'lt') %></span>票
    </p>
    <% if voted_entries(@event, 'lt').present? %>
      <p class="text-base mb-4 text-gray-600 text-left md:text-center">あなたが投票したのは以下のエントリーです</p>
      <ul class=" text-gray-700">
        <% voted_entries(@event, 'lt').each do |entry| %>
          <li class="py-1">
            <span><%= entry[:user_name] %></span>さんの「<%= entry[:title] %>」
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <% if @entries.present? %>
    <ul class="space-y-4">
      <% @entries.each do |entry| %>
        <li class="p-4 border border-gray-300 rounded-md flex justify-between items-center">
          <div>
            <p class="text-lg font-semibold"><%= entry.user.name %></p>
            <p class="text-gray-700"><%= entry.title %></p>
          </div>
          <%= link_to '選択する', event_entry_path(@event, entry, category: 'lt'), class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 inline-block min-w-[120px] text-center ml-5" %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center text-gray-500">エントリーされていません</p>
  <% end %>
</div>
<div class="mt-8 text-center">
  <%= link_to event_votes_categories_path(@event), class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>
<br>
<br>

app/views/entries/new_drink.html.erb
<div class="max-w-lg mx-auto p-4 bg-white shadow-sm sm:shadow-md rounded-md">
  <h1 class="text-3xl font-bold mb-6 text-center">酒王に登録</h1>
  <div class="text-xs">
    <% if user_entries_by_category(@event, @category.category_name).any? %>
      <i class="fa-solid fa-check"></i> 登録済みの作品<br>
      <ul>
        <% user_entries_by_category(@event, @category.category_name).each do |entry| %>
          <li><%= entry.title %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <% if flash[:error] %>
    <div class="mb-4 text-red-500">
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_with model: @entry, url: event_entries_path(@event), class: "space-y-4" do |form| %>
    <%= form.label :title, "作品名(お酒の名前)", class: "block font-medium mb-2" %>
    <%= form.text_field :title, class: "w-full border border-gray-300 rounded-md p-2" %>

    <%= form.label :description, "説明（アピールポイント）【任意】", class: "block font-medium mb-2" %>
    <%= form.text_area :description, rows: 5, class: "w-full border border-gray-300 rounded-md p-2" %>

    <%= form.label :image, "画像【任意】", class: "block font-medium mb-2" %>
    <%= form.file_field :image, class: "w-full" %>

    <%= form.hidden_field :category_id, value: @category.id %>
    <%= hidden_field_tag :category, @category.category_name %>
    <div class="text-center">
      <%= form.submit "登録する", class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 w-full sm:w-auto" %>
    </div>
  <% end %>
</div>

<div class="mt-14 text-center">
  <%= link_to event_entries_categories_path(@event), class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>

<br>
<br>

app/views/entries/new_food.html.erb
<div class="max-w-lg mx-auto p-4 bg-white shadow-sm sm:shadow-md rounded-md">
  <h1 class="text-3xl font-bold mb-6 text-center">飯王に登録</h1>
  <div class="text-xs">
    <% if user_entries_by_category(@event, @category.category_name).any? %>
      <i class="fa-solid fa-check"></i> 登録済みの作品<br>
      <ul>
        <% user_entries_by_category(@event, @category.category_name).each do |entry| %>
          <li><%= entry.title %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <% if flash[:error] %>
    <div class="mb-4 text-red-500">
      <%= flash[:error] %>
    </div>
  <% end %>

  <%= form_with model: @entry, url: event_entries_path(@event), class: "space-y-4" do |form| %>
    <%= form.label :title, "作品名（食べ物の名前）", class: "block font-medium mb-2" %>
    <%= form.text_field :title, class: "w-full border border-gray-300 rounded-md p-2" %>

    <%= form.label :description, "説明（アピールポイント）【任意】", class: "block font-medium mb-2" %>
    <%= form.text_area :description, rows: 5, class: "w-full border border-gray-300 rounded-md p-2" %>

    <%= form.label :image, "画像【任意】", class: "block font-medium mb-2" %>
    <%= form.file_field :image, class: "w-full" %>

    <%= form.hidden_field :category_id, value: @category.id %>
    <%= hidden_field_tag :category, @category.category_name %>

    <div class="text-center">
      <%= form.submit "登録する", class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600 w-full sm:w-auto" %>
    </div>
  <% end %>
</div>

<div class="mt-14 text-center">
  <%= link_to event_entries_categories_path(@event), class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>

<br>
<br>

app/views/entries/new_lt.html.erb
<div class="max-w-lg mx-auto p-4 bg-white shadow-sm sm:shadow-md rounded-md">
  <h1 class="text-3xl font-bold mb-6">LT王に登録</h1>
  <% if flash[:error] %>
    <div class="mb-4 text-red-500">
      <%= flash[:error] %>
    </div>
  <% end %>
  <%= form_with model: @entry,url: event_entries_path(@event), class: "space-y-4" do |form| %>
    <%= form.label :title, "LTのタイトル", class: "block font-medium mb-2" %>
    <%= form.text_field :title, class: "w-full border border-gray-300 rounded-md p-2" %>
    <%= form.hidden_field :category_id, value: @category.id %>
    <%= hidden_field_tag :category, @category.category_name %>
    <div class="text-center">
      <%= form.submit "登録する", class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600" %>
    </div>
  <% end %>
</div>
<div class="mt-14 text-center">
  <%= link_to event_entries_categories_path(@event), class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>

app/views/entries/show.html.erb
<div class="max-w-3xl mx-auto p-6 bg-white rounded-md shadow-sm md:shadow-md ">
  <h1 class="text-3xl font-bold mb-6">投票する</h1>
  <div class="mb-6">
  <% if @entry.image.attached? %>
    <%= image_tag @entry.image.variant(resize: "400x400"), class: "rounded-md" %>
  <% end %>
    <p class="text-2xl mt-2 font-bold">「<%= @entry.title %>」</p>
    <p class="text-2xl mt-2"><%= @name %></p>
    <p class="text-1xl mt-4 break-words"><%= @entry.description %></p>
  </div>
  <% if flash[:error].present? %>
    <div class="text-red-500">
      <%= flash[:error] %>
    </div>
  <% end %>
  <%= form_with model: @vote, url: event_votes_path(@event), class: "space-y-4" do |form| %>
    <div class="mb-4">
      <%= form.label :comment, "コメントを記入する【任意】", class: "block font-medium mb-2 text-gray-700" %>
      <%= form.text_area :comment, rows: 5, class: "w-full border border-gray-300 rounded-md p-2" %>
    </div>
    <%= form.hidden_field :entry_id, value: @entry.id %>
    <%= hidden_field_tag :category, @category %>
    <div class="text-center">
      <%= form.submit '投票する', class: "bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600" %>
    </div>
  <% end %>
</div>
<div class="mt-8 text-center">
  <%= link_to event_entries_path(@event, category: @category), class: 'btn btn-primary' do %>
    <i class="fa-solid fa-rotate-left"></i> 戻る
  <% end %>
</div>
<br>
<br>