config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  delete '/logout' => 'sessions#destroy'

  resources :events, only: [:show] do
    get 'votes/categories', to: 'votes#categories'
    get 'votes/completions', to: 'votes#completions'
    get 'entries/categories', to: 'entries#categories'
    get 'entries/completions', to: 'entries#completions'

    resources :entries, only: [:new, :create, :index, :show]
    resources :votes, only: [:create]
    resources :rankings, only: [:index]
    resources :comments, only: [:index, :show]
  end

  namespace :admin do
    resources :events, only: [:index, :new, :create, :show, :update]
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :entries, dependent: :destroy
  enum status: {
    preparing: 0,
    open: 1,
    counting: 2,
    closed: 3
  }
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < ApplicationController
    include AdminHelper
    before_action :require_admin
    before_action :set_event, only: %i[show update]

    def index
      @events = Event.order(created_at: :desc)
    end

    def show
      categories = %w[food drink lt]
      @rankings = {}

      categories.each do |category|
        votes = Vote.for_event(@event.id).for_category(category)

        @rankings[category] = {
          single: votes.ranking_by_single,
          total: votes.ranking_by_total_votes
        }
      end
    end

    def update
      if @event.update(update_event_params)
        redirect_to admin_event_path(@event), notice: 'ステータスを更新しました'
      else
        flash.now[:alert] = 'ステータスの更新に失敗しました'
        render :show, status: :unprocessable_entity
      end
    end

    def new
      @event = Event.new
    end

    def create
      @event = Event.new(create_event_params)
      if @event.save
        redirect_to admin_events_path, notice: 'イベントを作成しました'
      else
        flash.now[:alert] = 'イベントの作成に失敗しました'
        render :new, status: :unprocessable_entity
      end
    end

    private

    def set_event
      @event = Event.find(params[:id])
    end

    def create_event_params
      params.require(:event).permit(:title)
    end

    def update_event_params
      params.require(:event).permit(:status)
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :check_event_status

  def show
    @event = Event.find(params[:id])
  end
end

app/views/events/show.html.erb
<div class="px-4 text-center">
  <h1 class="text-3xl font-bold text-blue-700"><%= @event.title %></h1>
  <p class="mt-4 max-w-[390px] mx-auto sm:max-w-full leading-loose">
    このアプリでは<br>飯王と酒王への参加登録と<br>
    各カテゴリー（飯王・酒王・LT王）に<br>それぞれ最大3票まで投票できます。
  </p>
    <div class="text-center">
  <% if @event.closed? %>
    <h2 class="mt-8 text-2xl pb-5">投票結果</h2>
    <%= link_to event_rankings_path(@event), class: 'inline-flex items-center justify-center w-12 h-12 bg-blue-500 text-white rounded-full hover:bg-blue-700' do %>
      <i class="fa-solid fa-ranking-star"></i>
    <% end %>
  <% else %>
    <h2 class="mt-8 text-2xl pb-5">エントリーする</h2>
    <%= link_to event_entries_categories_path(@event), class: 'inline-flex items-center justify-center w-12 h-12 bg-blue-500 text-white rounded-full hover:bg-blue-700' do %>
      <i class="fa-solid fa-person fa-xl"></i>
    <% end %>
    <h2 class="mt-8 text-2xl pb-5">投票する</h2>
    <%= link_to event_votes_categories_path(@event), class: 'inline-flex items-center justify-center w-12 h-12 bg-blue-500 text-white rounded-full hover:bg-blue-700' do %>
      <i class="fa-solid fa-hand-holding-heart"></i>
    <% end %>
  <% end %>
  </div>
</div>